
package com.soap.client;

import java.awt.Image;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImageServer", targetNamespace = "http://image.poc.soap.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ImageServer {


    /**
     * 
     * @param path
     * @param imgUpload
     * @param name
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://image.poc.soap.org/ImageServer/uploadImageRequest", output = "http://image.poc.soap.org/ImageServer/uploadImageResponse")
    public String uploadImage(
        @WebParam(name = "data", partName = "data")
        Image imgUpload,
        @WebParam(name = "id", partName = "id")
        String id,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "path", partName = "path")
        String path);

    /**
     * 
     * @param name
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://image.poc.soap.org/ImageServer/downloadImageRequest", output = "http://image.poc.soap.org/ImageServer/downloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "name", partName = "name")
        String name);

}
