//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.25 at 01:56:54 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.com/spring/boot/soap/mtomresponse/models/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.spring.boot.soap.mtomresponse.models.user;
